src/layers/TrafimageRasterLayer/TrafimageRasterLayer.js
Reverts geops/trafimage-maps#18
=> Revert "Renaming the url parameter `key` to `token`."

package.json, src/__snapshots__/AppRouter.test.js.snap, src/components/Menu/Menu.js, src/components/Menu/TopicMenu.js, src/components/Menu/TopicMenu.scss, src/config/layers.js, yarn.lock
- Changing the initial layer visibility.
- Hiding layers in legend.
- Restore visibility from permalink.
=> Updates for layers.

package.json, src/__snapshots__/AppRouter.test.js.snap, src/components/Popup/Popup.js, src/components/TopicLoader/TopicLoader.js, src/components/TrafimageMaps/TrafimageMaps.js, src/config/layers.js, src/layers/NetzkartePointLayer/NetzkartePointLayer.js, yarn.lock
Popup only for visible layers.
=> Feature info based on promises.

package.json, src/config/appConfig.js, src/config/instances.js
The tag "stele" is used for docker-containers building with this env.
=> Be consistent with environment name for stele

src/AppRouter.js, src/__snapshots__/AppRouter.test.js.snap, src/components/Menu/Menu.scss, src/components/Menu/MenuHeader.scss, src/components/Menu/MenuItem.scss, src/components/Menu/TopicMenu.scss, src/components/TopicLoader/TopicLoader.js, src/config/instances.js, src/config/topics.js
Topics that link to the old wkp.
To be removed after the migration is finished.
=> Link topics

package.json, src/__snapshots__/AppRouter.test.js.snap, src/components/Menu/TopicMenu.js, src/components/Menu/TopicMenu.scss, src/components/TrafimageMaps/TrafimageMaps.scss, src/config/layers.js, src/layers/ZoneLayer/ZoneLayer.js, yarn.lock
Wait for deploy of new react-spaital
=> Only display baseLayers in legend on mobile

package.json, public/lang/locale-de-main.json, public/lang/locale-en-main.json, public/lang/locale-fr-main.json, public/lang/locale-it-main.json, src/components/Popup/Popup.js, src/components/Popup/Popup.scss, yarn.lock
Require this react-spatial MR to be merged: https://github.com/geops/react-spatial/pull/223
=> Allow pagination in WKP Popup, when several features are clicked

package.json, src/components/Permalink/Permalink.js, src/components/Popup/Popup.js, yarn.lock
See also https://github.com/geops/react-spatial/pull/231
=> Remove obsolete permalink functionality.

src/AppRouter.js, src/__snapshots__/AppRouter.test.js.snap, src/components/Share/Share.js, src/components/TopicsMenu/TopicsMenu.js, src/components/TrafimageMaps/TrafimageMaps.js, src/config/topics.js
THis PR:
- fix CanvasSaveButton
- manage 'disabled' permalink, this parameterr has priority over topic configuraton.
- allow to disable elements shareMenu TrackerMenu, featureMenu form topic's configuration:
```
export const netzkarte = {
name: 'ch.sbb.netzkarte',
key: 'ch.sbb.netzkarte',
elements: {
...defaultElements,
popup: true,
shareMenu: true,
trackerMenu: true,
featureMenu: true,
},
```
- add `subMenus` and `menus` parameters to `trafimage-maps` component to be allow to add additional menus.
=> Add disbaled permalink parameter

src/AppRouter.js, src/apps/Casa/README.md, src/apps/TrafimageWKP/README.md, src/components/TopicElements/TopicElements.js, src/components/TopicElements/index.js, src/components/TopicLoader/TopicLoader.js, src/components/TrafimageMaps/README.md, src/components/TrafimageMaps/TrafimageMaps.js, src/config/Casa.js, src/config/examples/TrafimageMaps/topics.js
* Move loading of topic elements into separate component.
* Move elements into topic config.
* Remove unused props from TrafimageMaps component.
Please test for edge cases.
=> Cleanup topic loading

src/components/TopicLoader/TopicLoader.js, src/layers/layerHelper.js, src/searches/Lines/Lines.js, src/searches/Search.js
Allowing custom search stylings for implementing resolution dependent styling of line search.
=> Allow custom search styles.

src/__mocks__/mapbox-gl.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.js, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
Replace https://github.com/geops/trafimage-maps/pull/318
=> Fix visibility of mapbox layer

src/components/FeatureInformation/FeatureInformation.js, src/popups/DeparturePopup/DeparturePopup.js
Allow to redirect to netzkarte popup, when closing departure popup.
=> REturn to netzkarte Popup on departure popup close with close button.

src/components/Footer/Footer.js, src/components/Footer/Footer.scss
In combination with https://github.com/geops/react-spatial/pull/429 (@edellucien) and https://github.com/geops/react-spatial/pull/418 (@oterral)
=> Fix copyright styling

src/components/Permalink/Permalink.js, src/components/Share/Share.js, src/components/Share/Share.scss, src/components/Share/__snapshots__/Share.test.js.snap, src/components/TopicElements/TopicElements.js, src/components/TopicLoader/TopicLoader.js, src/layers/layerHelper.js, src/menus/ShareMenu/ShareMenu.js, src/menus/ShareMenu/ShareMenu.scss
This reverts commit 32622efa1c91934229cb6a60947e93390bb5e67e, reversing
changes made to 8837ec3a14896103dc08cec733b3a290253cff6c.
=> Revert "Merge pull request #346 from geops/lucien/drawing_button"

src/components/Permalink/Permalink.js, src/components/Share/Share.js, src/components/TopicLoader/TopicLoader.js, src/config/topics.js, src/layers/layerHelper.js, src/utils/redirectHelper.js
Combination of [drawing button](https://github.com/geops/trafimage-maps/tree/lucien/drawing_button) (as Revert of [lucien/revert_draw](https://github.com/geops/trafimage-maps/tree/lucien/revert_draw)) and redirection
=> Core: Redirect to old wkp

.dependabot/config.yml
Set update interval to `weekly` and set default reviewers and assignee.
Feel free to adapt the config as needed.
Dokumentation: https://dependabot.com/docs/config-file/
=> Create dependabot config

src/layers/RouteLayer/RouteLayer.js
=> fix routing url

src/components/TopicMenu/TopicMenu.js
- Change property name of LayerTree
=> Update react-spatial to 0.1.1-beta.22 II

src/components/Footer/Footer.js, src/popups/NetzkartePopup/NetzkartePopup.js, src/utils/coordinateHelper.js, src/utils/coordinateHelper.test.js
WIP: As soon as the react-spatial [PR](https://github.com/geops/react-spatial/pull/482) is merged, I can create a new react-spatial version and integrate it here.
=> Mouse position: Use default projection from redux in mouse position

src/components/Map/Map.js, src/components/TopicElements/TopicElements.js, src/components/TrafimageMaps/TrafimageMaps.js, src/layers/CasaLayer/CasaLayer.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.js, src/popups/BehigPopup/BehigPopup.js, src/popups/DeparturePopup/DeparturePopupContent.js, src/popups/DeparturePopup/DestinationInput.js, src/searches/HandicapNoInfoFinder/HandicapNoInfoFinder.js
- Marked parameters to omit in documentation as @private
=> Clean documentation

src/examples/Casa/casa.css
- Last adjustment to casa style
- added hover css on map controls in casa css
=> CASA hover style

src/components/Map/Map.js, src/components/Search/Search.js, src/components/Search/Search.scss, src/components/Search/SearchToggle.js, src/components/TopicsMenu/TopicsMenu.js, src/model/app/actions.js, src/model/app/reducers.js
- Moved searchOpen variable to Redux
- Dispatching setSearchOpen to false on Click on map, on menu button, on result select (click and key) and on reset search input.
=> Collapse Search on Click

src/examples/Casa/README.md, src/layers/CasaLayer/CasaLayer.js, src/layers/RouteLayer/RouteLayer.js, src/layers/RouteLayer/RouteLayer.test.js
- Filtering features on isClickable, preventing the mouse from updating to pointer
=> Default cursor on not clickable zone

src/popups/HandicapPopup/HandicapPopupElement.js
Add http to handicap href link only when not initially present.
=> Only add http to link href when missing initially

package.json, yarn.lock
* Downgraded @webcomponents/custom-elements from 1.4.0 to 1.3.2
=> rolling back custom-component lib to 1.3.2

src/popups/HandicapPopup/HandicapPopup.scss, src/popups/HandicapPopup/HandicapPopupElement.js, src/popups/HandicapPopup/HandicapPopupElement.test.js
Solved: 
- add break tag for empty lines in popup content
- telephone regex problem
- add tests for telephone regex & http regex
=> Interpret empty lines as break tag for popup content

package.json, src/components/Footer/Footer.js, src/components/Footer/Footer.scss, src/components/Header/Header.scss, src/components/Search/Search.js, src/components/Search/Search.scss, src/components/Search/SearchToggle.scss, src/components/TopicMenu/TopicMenu.scss, src/components/TrafimageMaps/TrafimageMaps.scss, yarn.lock
- Redefined base layer dropdown width (preventing container overflow)
- Using renderInputComponent prop for AutoSuggest, using flexBox to improve CSS
- Removed setSearchOpen dispatch on search clear button
- Improved Search component centering
- Removed Developer Portal link from footer on small screens
=> iPhone & Search fix

package.json, src/components/TopicLoader/TopicLoader.js, src/components/TopicMenu/TopicMenu.js, src/components/TopicMenu/TopicMenu.scss, src/components/TrafimageMaps/TrafimageMaps.js, src/globals.scss
- close popup on topic changes
- menu padding as old wkp menu
- grey out inactive topic titles
- ie fix for lock icons
- redirect fix
=> Redirect plus various fixes

public/index.html
Development box to hide all app interaction buttons
=> Create development box for app interaction buttons

src/layers/layerHelper.js, src/layers/layerHelper.test.js
Search for 200 12-35, highlight the line on various zooms
=> Fix gen levels

src/README.md, src/WebComponent.js, src/components/TopicMenu/TopicMenu.js, src/components/TrafimageMaps/TrafimageMaps.js
- Removed maxExtent from the WebComponent documentation
- Updated the maxExtent parameter description
=> maxExtent documentation

src/components/Share/Share.js, src/components/Share/Share.scss, src/components/Share/Share.test.js, src/components/Share/__snapshots__/Share.test.js.snap, src/lang/fr.json, src/lang/it.json
The quickstart Link is supposed to be displayed only for intern topic. But for you to test i display it for public topic first.
Then when you accept the MR I will switch the display for internal and edit the tests.
=> WIP Add Manual link in ShareMenu

package.json, src/components/Dialog/Dialog.scss, src/components/FeatureInformation/FeatureInformation.scss, src/components/LayerInfosDialog/LayerInfosDialog.js, src/components/LayerInfosDialog/__snapshots__/LayerInfosDialog.test.js.snap, src/components/MainDialog/MainDialog.js, src/components/TrafimageMaps/TrafimageMaps.scss, yarn.lock
=> WIP Try to solve dialog height without vh/vw

src/config/topics.js
Forgot to merge into the release branch first
see https://github.com/geops/trafimage-maps/pull/658/
=> Zweitausbildung: Restrict max zoom to 13 (merge into release branch)

package.json, src/components/FeatureInformation/FeatureInformation.js, src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap
=> Merge master into handicap

package.json, src/components/IconList/IconList.js, src/components/TrafimageMaps/TrafimageMaps.js, src/layers/layerHelper.js
=> Clean doc, exclude private comments

package.json, src/WebComponent.js, src/menus/TrackerMenu/TrackerMenu.js, yarn.lock
=> WIP: Lucien/lazy load fix

src/menus/TrackerMenu/TrackerMenu.js
=> Re-intialize click on layers change

package.json, src/components/TopicLoader/TopicLoader.js, src/config/layers.js, src/examples/Casa/topic.js, src/examples/Punctuality/layers.js, src/layers/TrafimageGeoServerWMSLayer/TrafimageGeoServerWMSLayer.js, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js, src/layers/ZweitausbildungAbroadLayer/ZweitausbildungAbroadLayer.js, src/layers/ZweitausbildungPoisLayer/ZweitausbildungPoisLayer.js, src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js, yarn.lock
=> Use react-spatial v0.3.1

package.json, yarn.lock
=> Fix Documentation

package.json, src/config/layers.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.js, yarn.lock
Update react-spatial, fixes 2 bugs:
- resize the map when the window is resized 
- the passagiergfrequenzen layer is displayed at loading then disappear if we load another topic
[Before](https://deploy-preview-629--dev-trafimage-maps.netlify.app/?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.landeskarte.grau,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.luftbild.group&lang=de&layers=ch.sbb.bahnhoffrequenzen&x=815541.66&y=5896394.08&z=11)
[After](https://deploy-preview-691--dev-trafimage-maps.netlify.app/?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.landeskarte.grau,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.luftbild.group&lang=de&layers=ch.sbb.bahnhoffrequenzen&x=815541.66&y=5896394.08&z=11)
=> Update react-spatial to 0.3.3

src/components/TrafimageMaps/TrafimageMaps.scss
=> Release 1.1 Switcher box-shadow

cypress/integration/Header.spec.js
Cypress test for header should successfully run
=> Test header elements with cypress

src/config/layers.js, src/examples/Casa/topic.js
=> Use bright style

src/components/Map/Map.js, src/components/MapAccessibility/MapAccessibility.js, src/components/MapAccessibility/index.js, src/components/TrafimageMaps/TrafimageMaps.scss, src/config/layers.js
Features on Pünktlichkeit layers should be accessible by hitting tab and enter keys.
=> Map accessibility component

src/components/MapAccessibility/MapAccessibility.js, src/components/TopicElements/TopicElements.js
The map is selected after the search field using the tab key now. Also on the Pünktlichkeits-Layer trajectories will be better selectable now.
=> Improve a11y selection

package.json, src/components/Map/Map.js, src/config/layers.js, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/layers/LevelLayer/LevelLayer.js, src/layers/LevelLayer/index.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.js
=> Add LevelLayer for new sandbox topic

package.json, yarn.lock
Fix tab navigation for punctuality layer.
=> Use react-spatial v0.4.2-beta.1. Fix punctuality tab navigation

yarn.lock
Co-authored-by: Renovate Bot <bot@renovateapp.com>
=> Update dependency lodash to v4.17.19 [SECURITY] (#733)

src/examples/Casa/README.md, src/layers/RouteLayer/RouteLayer.js
Flag marker in CASA routes should only be set in the final sequence of the route.
=> Route flag marker fix

src/components/MapAccessibility/MapAccessibility.js, src/layers/LevelLayer/LevelLayer.js
Ticket:TRAFDOKU-54
Remove bother layers from layer docu
=> Remove MapAccessibility & LevelLayer from Layers docu

src/config/layers.js, src/layers/ParksLayer/ParksLayer.js, src/layers/ParksLayer/index.js, yarn.lock
- Hover effect for parks layer
=> Initial commit to add hover effect on parks layer

src/components/Search/Search.scss
Clear button for the search bar is hidden behind the search button.
Ticket: TRAFWART-858
=> Hotfix the search clear button

src/__mocks__/mapbox-gl.js, src/config/layers.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.js, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
Fix the display of MapBoxStyleLayer
=> Clean loading event mess

src/WebComponent.scss
We don't load the fonts internally but directly from the sbb cdn
=> Load font directly from SBB CDN

package.json, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
A bad content was append to the style url:
https://maps.geops.io/data/relief_white/8/131/89.jpg?key=blabla/styles/netzkarte_personenverkehr_v3/style.json
Theis PR fix this.
=> Fix mapbox style loading

src/examples/Casa/README.md
Open casa example and see that there is no more menu
=> Remove menu from casa

cypress/integration/Handicap.spec.js
Add Cypress test for handicap station search
=> Add Cypress test for handicap station search

package.json, yarn.lock
=> Update geops-docjs-template to 1.0.4

src/components/TopicsMenu/TopicsMenu.scss
=> Raise topic menu max height

src/config/layers.js
Simplified the radius calculation (no more interpolation)
=> simplified radius calc

package.json, src/config/layers.js, src/searches/Betriebspunkte/Betriebspunkte.js, src/searches/HandicapStopFinder/HandicapStopFinder.js, src/searches/Lines/Lines.js, src/searches/Locations/Locations.js, src/searches/Municipalities/Municipalities.js, src/searches/StopFinder/StopFinder.js, yarn.lock
=> Lucien/release 1.3 fix

src/components/FeatureInformation/FeatureInformation.js, src/components/FeatureInformation/FeatureInformation.scss, src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap, src/popups/HandicapPopup/HandicapPopup.js, src/popups/HandicapPopup/HandicapPopupElement.js, src/popups/HandicapPopup/HandicapPopupElement.test.js, src/popups/HandicapPopup/__snapshots__/HandicapPopupElement.test.js.snap
=> Allow to navigate with tab on all handicap popup content

package.json, src/components/TopicMenu/TopicMenu.js, src/components/TopicMenu/TopicMenu.scss, src/components/TrafimageMaps/TrafimageMaps.scss, src/examples/Casa/casa.css, src/filters/AusbauFilters/AusbauFilters.js, src/filters/AusbauFilters/__snapshots__/AusbauFilters.test.js.snap
=> Changes css of AubsauFilters 2

package.json, src/examples/Casa/casa.css, yarn.lock
Using new react-spatial version including updated Zoom component
=> CASA Updates + Zoom button disable

package.json, src/components/MapControls/MapControls.scss
=> Web Component Zoom Btn CSS fix

package.json, src/components/Footer/Footer.scss, src/components/Link/Link.scss, src/components/Search/Search.scss, src/components/Share/Share.scss, src/components/TopicMenu/TopicMenu.scss, src/components/TrafimageMaps/TrafimageMaps.scss, src/menus/TrackerMenu/TrackerMenu.js, src/menus/TrackerMenu/TrackerMenu.scss, src/popups/HandicapPopup/HandicapPopup.scss, yarn.lock
=> Use copyright footer in RouteScheduler

src/config/layers.js
=> Use base_bright_v2 for showcase topic

package.json, src/components/FeatureInformation/FeatureInformation.js, src/components/Popup/Popup.js
Add new property 'modifyPopupFeatures' to layer, to be able to modify popup features.
Example merge all features into one Feature, to show them all in one popup (zweitausbildung pois)
=> Add new property 'modifyPopupFeatures'

src/searches/Betriebspunkte/Betriebspunkte.js, src/searches/Lines/Lines.js, src/searches/Locations/Locations.js, src/searches/Municipalities/Municipalities.js
=> Set default search url

src/filters/AusbauFilters/AusbauFilters.js, src/filters/AusbauFilters/AusbauFilters.test.js, src/filters/AusbauFilters/__snapshots__/AusbauFilters.test.js.snap, src/layers/AusbauLayer/AusbauLayer.js, src/layers/AusbauLayer/AusbauLayer.test.js
- On [prod](https://maps2.trafimage.ch/ch.sbb.construction?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.luftbild.group&lang=de&layers=ch.sbb.construction.unterhalt.uebrige,ch.sbb.construction.unterhalt.bahnhof_strecke,ch.sbb.construction.unterhalt.strecke,ch.sbb.construction.unterhalt.bahnhof,ch.sbb.construction.ausbau.uebrige,ch.sbb.construction.ausbau.bahnhof_strecke,ch.sbb.construction.ausbau.strecke,ch.sbb.construction.ausbau.bahnhof&x=965968.19&y=6002627.42&z=12.180000000000001) there is bau projekte display around Uster
- With this PR open [preview](https://deploy-preview-849--dev-trafimage-maps.netlify.app/?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.luftbild.group,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.landeskarte.grau&lang=de&layers=&x=971600.73&y=6000321.96&z=12)
- …
=> Use defaultFilter when filter param doesn't exist

src/config/layers.js
=> Switch from showcase2 to new style 'base_dark_v2

package.json, src/menus/TrackerMenu/TrackerMenu.scss, yarn.lock
Ticket: TGSRVI-575
- Update mobility toolbox to get a better adaptation of the font size in the vehicule bubbles, for long name, for the punctuality layer.
Can be tested in Fernverkehr sub Layer, in the Netherlands for instance
- Change bubble display to fit long names in perlenkette menu.
=> Better font adaptation for Tracker layer

package.json, src/components/FeatureInformation/FeatureInformation.js, src/components/Popup/Popup.js, src/config/topics.js, src/examples/Casa/README.md, src/layers/CasaLayer/CasaLayer.js, src/layers/CasaLayer/CasaLayer.test.js, src/layers/RouteLayer/RouteLayer.js, src/layers/RouteLayer/RouteLayer.test.js, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js, src/popups/CasaRoutePopup/CasaRoutePopup.js, src/popups/CasaRoutePopup/CasaRoutePopup.scss, src/popups/KilometragePopup/KilometragePopup.js, yarn.lock
CASA should have support for coordinates instead of stations in the route sequences configuration.
=> CASA foot routing

package.json, public/index.html, src/WebComponent.js, src/components/Login/Login.js, src/components/Login/Login.test.js, src/components/TopicLoader/TopicLoader.js, src/components/TrafimageMaps/TrafimageMaps.js, src/model/app/actions.js, src/model/app/reducers.js
=> WIP: remove permission check from github

src/config/layers.js
Define unique keys to showcase layers
=> Define unique keys to showcase layers

package.json, src/components/Map/Map.js, src/components/Permalink/Permalink.js, src/components/TopicLoader/TopicLoader.js, src/components/TopicMenu/TopicMenu.js, src/layerInfos/ZweitausbildungLayerInfo/ZweitausbildungLayerInfo.js, src/layerInfos/ZweitausbildungRoutesSubLayerInfo/ZweitausbildungRoutesSubLayerInfo.js, src/layerInfos/ZweitausbildungSubLayerInfo/ZweitausbildungSubLayerInfo.js, src/layerInfos/ZweitausbildungTopicInfo/ZweitausbildungTopicInfo.js, src/menus/TrackerMenu/TrackerMenu.js, src/popups/BahnhofplanPopup/BahnhofplanPopup.js, src/popups/BehigPopup/BehigPopup.js, src/popups/DeparturePopup/DeparturePopupContent.js, src/popups/ParksPopup/ParksPopup.js, src/popups/ZweitausbildungAbroadPopup/ZweitausbildungAbroadPopup.js, src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.js, src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.js
Replace lodash compose by redux's compose.
Remove lodash completely
Ticket: TRAFKLEIN-500
=> Replace lodash compose by redux's compose. Remove lodash completely

package.json, yarn.lock
Fix the documentation . When we switched from casa to construction demo, the map blinked infinitely
=> Update mobility-toolbox v1.2.3

package.json, src/components/TopicLoader/TopicLoader.js, src/config/layers.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.js, src/layers/MapboxStyleLayer/MapboxStyleLayer.test.js, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js, yarn.lock
Mobility-toolbox-js updated for apiKey handling
Prevent to request without apiKey defined
Introduce new param to MapboxStyleLayer, to be bale to switch MapboxLayer style.
=> Avoid fail fetch when no apiKey

src/components/LanguageSelect/LanguageSelect.js
Set black color for selected Option
Set red color for hovered Option
Ticket: TRAFWART-973
=> Better language Select colors

package.json, yarn.lock
=> Update react-spatial to v1.0.19 - Unlisten layerService correctly

package.json, src/components/Share/Share.js, src/components/Share/__snapshots__/Share.test.js.snap
Encode shared url
To fix: shared url via twitter
=> Encode shared url

package.json, src/components/TopicLoader/TopicLoader.js, src/model/app/reducers.js
When switching topics, the layers was set too many times in thre LayerService
=> Fix loading of topics avoiding too much load

src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
Fix filters loading when mbMap not yet loaded
Ticket: TRAFWART-986
=> Fix filters loading when mbMap not yet loaded

src/config/layers.js
Use sbb version von tracker Api.
Ticket: TGSRVI-659
=> Use sbb version von tracker Api

src/components/Share/Share.js, src/components/Share/Share.scss, src/components/Share/Share.test.js, src/lang/de.json, src/lang/fr.json, src/lang/it.json
[TRAFDOKU-68] Remove quickstart manual button
=> [TRAFDOKU-68] Remove quickstart manual button

package.json, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/layerInfos/PunctualityLayerInfo/PunctualityLayerInfo.js, src/layerInfos/PunctualityLayerInfo/PunctualityLayerInfo.scss, yarn.lock
Use new mobility-toolbox-js version:
https://github.com/geops/mobility-toolbox-js/pull/114
Cancelled trains have dashed circles instead of crossed circle
Update legend accordingly
Ticket: TRAFKLEIN-535
=> New punctuality vehicules legend

package.json, src/components/LayerInfosDialog/__snapshots__/LayerInfosDialog.test.js.snap, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js, yarn.lock
Fix yarn lock and depenencies.
Republish version that worked with test repo:
https://github.com/oterral/angular-react-test
=> Republish and fix previous compiled version

src/components/Link/Link.js, src/components/Link/__snapshots__/Link.test.js.snap, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/popups/HandicapPopup/HandicapPopup.js, src/popups/HandicapPopup/__snapshots__/HandicapPopupElement.test.js.snap
Add tourist offer links in the handicap popup
=> Accessible tourist offers in handicap popup

src/popups/HandicapPopup/HandicapPopup.js
Publishing Cartaro vector tile data only allows serialization into types String, Number or Boolean, resulting in array data as a String. We therefore need to parse the string in the frontend
=> Parse tourist offer data string in popup

src/components/FeatureInformation/FeatureInformation.js, src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.js
=> Manage multiple layers when hidePagination is set for a popup

package.json, src/components/FeatureInformation/FeatureInformation.js, src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.js
Introduce `hidePagination` popup property, display all popup items for zweitausbildung pois without pagination.
=> Disable pagination for zweitausbildung poi popup.

src/examples/Casa/README.md, src/layers/RouteLayer/RouteLayer.js
=> CASA foot routing updates

package.json, src/config/layers.js, src/config/topics.js, src/layers/StationsLayer/StationsLayer.js, src/layers/StationsLayer/index.js, styleguide.config.js
- Open [review app](https://deploy-preview-906--trafimage-maps.netlify.app/?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.dark,ch.sbb.netzkarte.luftbild.group,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.landeskarte.grau&lang=de&layers=&utm_campaign=bot_dp&utm_source=github#/Examples/Casa%20Map)
- try to click on a stations point 
---> a blue point should appear on hover then a popup on click
=> Add possibitlity to click station in CASA topic

src/components/TrafimageMaps/TrafimageMaps.scss
=> Copyright lint fix

package.json, src/components/Collapsible/Collapsible.js, src/components/ExportButton/ExportButton.test.js, src/components/TopicLoader/TopicLoader.js, src/config/topics.js, src/examples/Casa/README.md, src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
=> Improve loading of casa topic

src/components/TopicLoader/TopicLoader.js, src/components/TrafimageMaps/TrafimageMaps.js, src/model/map/reducers.js
=> Properly remove layers and their listeners on unmount

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/popups/BahnhofplanPopup/BahnhofplanPopup.js, src/popups/NetzkartePopup/NetzkartePopup.js
- Open preview
- Click on station that has a url_bep property
- Click on the link "Bahnersatzplan"
--> A pdf will be downloaded
=> Add url_bep to station links

src/popups/BahnhofplanPopup/BahnhofplanPopup.js, src/popups/NetzkartePopup/NetzkartePopup.js
Follow https://github.com/geops/trafimage-maps/pull/915
=> Move bahnhofsatzplan one level higher

src/popups/NetzkartePopup/NetzkartePopup.js
=> Remov pdf icon

src/components/LayerInfosDialog/LayerInfosDialog.js, src/config/topics.js, src/lang/fr.json, src/lang/it.json
=> Netzentwicklung

src/components/Search/Search.js, src/searches/Lines/Lines.js
=> Search value on suggestion click fix

src/components/Map/Map.js, src/components/Permalink/Permalink.js, src/components/Popup/Popup.js, src/model/app/actions.js, src/model/app/reducers.js
A permalink parameter needs to be added that blocks all popups
=> Block Popups parameter

src/layerInfos/NetzentwicklungLayerInfo/NetzentwicklungLayerInfo.js, webComponent.html
=> Hardcode netzentwicklung colors

src/searches/Betriebspunkte/Betriebspunkte.js
The abbreviation needs to be displayed in the Betriebspunkte search results
=> Abbreviation in Betriebspunkte search results

package.json
=> Publish version 1.6.6

styleguide.config.js
=> Change naming of direct connections in doc

package.json, public/index.html, src/components/Overlay/Overlay.js, yarn.lock
Fix a small css bug for overlay
=> Fix css of overlay when there is no header and footer

.env, package.json, src/components/Search/Search.js, src/components/Search/SearchService.js, src/searches/Locations/Locations.js, src/searches/StopFinder/StopFinder.js, yarn.lock
Keep track of the selected suggestions
=> Click on search button zoom on selected suggestion

package.json, public/iframe.html, public/index.html, src/components/Map/Map.js, src/components/NoDragPanWarning/NoDragPanWarning.js, src/components/NoMouseWheelWarning/NoMouseWheelWarning.js, src/components/NoMouseWheelWarning/NoMouseWheelWarning.test.js, src/components/NoMouseWheelWarning/index.js
When embedded= true on mobile the parent page can't be scrolled. THis PR fixes it.
=>  Fix scrolling on mobile when embedded is true

src/popups/DirektverbindungPopup/DirektverbindungPopup.js
The Direktbverbindungen Popup should, if provided, display the description and link of the connection in the Popup Overlay
=> Draft: Direktverbindungen description and link

src/components/FeatureInformation/FeatureInformation.js, src/components/LayerInfosDialog/__snapshots__/LayerInfosDialog.test.js.snap, src/popups/DeparturePopup/DeparturePopup.js, src/popups/MapsGeoAdminPopup/MapsGeoAdminPopup.js, src/popups/NetzentwicklungPopup/NetzentwicklungPopup.js, src/popups/NetzkartePopup/NetzkartePopup.js, src/popups/RegionenkarteSegmentPopup/RegionenkarteSegmentPopup.js, src/popups/StationPopup/StationPopup.js, src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.js, src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.js
Add the layer to the renderTitle parameters in the Popup
=> Popup renderTitle layer param

public/index.html, src/components/FeatureInformation/FeatureInformation.js, src/components/FeatureInformation/FeatureInformation.test.js, src/layerInfos/ZweitausbildungLayerInfo/ZweitausbildungLayerInfo.js, src/layers/RouteLayer/RouteLayer.test.js
=> Recenter when selected features are hidden by lements

package.json, src/components/PersonCard/PersonCard.js, src/components/PersonCard/index.js, src/popups/BeleuchtungsPopup/BeleuchtungsPopup.js, src/popups/NetzentwicklungPopup/NetzentwicklungPopup.js, src/popups/RegionenkarteSegmentPopup/Av.js, src/popups/RegionenkarteSegmentPopup/Nl.js, src/popups/RegionenkarteSegmentPopup/Person.js, src/popups/RegionenkarteSegmentPopup/Region.js, src/utils/formatPhone.js
Since the Person component from Netzentwicklung and Bahnnahes Bauen will be reused in future topic (BPS, Energie) a generic and reusable PersonCard component has been added and used accordingly in the topics
=> PersonCard component

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json
Updated translations for BPS topic name
=> fix(BPS): update BPS topic name

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json
New translation for Induktionsverstärker
=> fix(handicap): updated equipment translations

src/components/MapControls/MapControls.js
=> fix: check if orientation event is absolute

src/components/Map/Map.js, src/components/TopicElements/TopicElements.js, src/components/TopicMenu/TopicMenu.js, src/components/TopicMenu/TopicMenu.test.js, src/components/TopicsMenu/TopicsMenu.js, src/components/TopicsMenu/TopicsMenu.test.js, src/components/TopicsMenuHeader/TopicsMenuHeader.js, src/components/TopicsMenuHeader/TopicsMenuHeader.test.js, src/config/ch.sbb.zweitausbildung/index.js, src/utils/LayerService.js, src/utils/LayerService.test.js
Since the LayerrService was migrated into Trafimage and the change:visible listeners were commented out, the TopicMenuHeader can no longer listen to this event and the subtitle does not update
=> fix: display correct subtitle in menu header

.env, public/index.html, src/WebComponent.js, src/components/TopicLoader/TopicLoader.js, src/components/TrafimageMaps/TrafimageMaps.js, src/model/app/actions.js, src/model/app/reducers.js
=> fix: add new url parameters for development

package.json, src/layerInfos/BetriebsRegionenLayerInfo/BetriebsRegionenLayerInfo.js, src/layerInfos/DirektVerbindungenLayerInfo/DirektVerbindungenLayerInfo.js, src/layerInfos/InfrastrukturTopicInfo/InfrastrukturTopicInfo.js, src/layers/TarifverbundkarteLayer/TarifverbundkarteLayer.js
=> fix: updated data source dates in DV and Eisenbahninfrastruktur TopicInfos

src/layerInfos/TarifverbundkarteTopicInfo/TarifVerbundLegend.js
=> fix(Tarifverbundkarte): add key to style fetch for Tarifverbundkarte legend

package.json, src/components/DataLink/DataLink.js, src/components/LayerInfosDialog/LayerInfosDialog.js, src/components/Link/Link.js, src/components/Link/Link.scss, src/components/Link/__snapshots__/Link.test.js.snap, src/config/ch.sbb.netzkarte/index.js, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/layerInfos/ConstructionTopicInfo/ConstructionTopicInfo.js, src/layerInfos/DirektVerbindungenLayerInfo/DirektVerbindungenLayerInfo.js, src/layerInfos/HandicapTopicInfo/HandicapTopicInfo.js, src/layerInfos/NetzentwicklungTopicInfo/NetzentwicklungTopicInfo.js, src/layerInfos/PassagierFrequenzenLayerInfo/PassagierFrequenzenLayerInfo.js, src/layerInfos/TarifverbundkarteTopicInfo/TarifverbundkarteTopicInfo.js, src/menus/StsMenu/StsMenu.js, src/menus/StsMenu/StsValidityLayerSwitcher.js, src/popups/HandicapPopup/__snapshots__/HandicapPopupElement.test.js.snap
=> fix: add data links for various topics and layers in Info components 

src/README.md, src/components/Permalink/Permalink.js, src/components/Permalink/Permalink.test.js, src/examples/Punctuality/README.md, src/layers/TralisLayer/TralisLayer.js
=> docs: fix links in documentation (web component, punctuality)

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/popups/GeltungsbereicheGaPopup/GeltungsbereicheLegend.js
=> fix(Geltungbereiche): add translation for subway

.github/workflows/cypress-chrome.yml, src/layerInfos/IsbTopicInfo/IsbTopicInfo.js, yarn.lock
Add data link to ISB Topic Info
=> fix(ISB): add open data link in topic info

.github/workflows/cypress-chrome.yml, .github/workflows/cypress-edge.yml, .github/workflows/cypress-firefox.yml, src/config/ch.sbb.netzkarte.sandbox/index.js, src/layers/LevelLayer/LevelLayer.js
Open sandbox topic
-> zoom on Bern station 
-> change the background to ROKAS-Pois
=> feat: add rokas poi background layer in sandbox topic

src/components/LegalLines/Imprint/Imprint.js, src/components/LegalLines/__snapshots__/LegalLines.test.js.snap
Open Impressum and check the geOps url
=> fix: update geops address

package.json, src/layerInfos/NetzentwicklungLayerInfo/NetzentwicklungLayerInfo.js, src/layers/DirektverbindungenLayer/DirektverbindungenLayer.js, src/popups/RegionenkarteSegmentPopup/Av.js
=> fix(cartaro requests): use tyke cache url instead of cartaro items endpoint

src/layerInfos/NetzentwicklungLayerInfo/NetzentwicklungLayerInfo.js, src/layers/DirektverbindungenLayer/DirektverbindungenLayer.js
=> fix: fetch netzentwicklung and dv metadata from mapbox metadata

CHANGELOG.md, package.json
=> chore(release): v1.21.6

package.json, src/config/ch.sbb.direktverbindungen/DvListButton/DvListButton.js
=> fix(Direktverbindungen): always sync dv features on list open

package.json, src/WebComponent.js, src/components/TopicLoader/TopicLoader.js, src/components/TopicMenu/TopicMenu.js, src/config/topics.js, src/utils/applyPermalinkVisibility.js
Works loclly but not on the review app, no idea why
You should not see the base light layer before seeing the dark one.
=> fix: initialize properly the background visibility

src/layerInfos/GeltungsbereicheTopicInfo/GeltungsbereicheTopicInfo.js
=> fix: update Geltungsbereiche layer info translations

src/components/ExportButton/exportUtils.js, src/config/topics.js
=> fix(export): make export file name configurable in the topic config

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/layerInfos/GeltungsbereicheLayerInfo/GeltungsbereicheLayerInfo.js
Add info text in GB LayerInfos
=> fix(Geltungsbereiche): add Detail in LayerInfo footer

package.json, src/config/ch.sbb.handicap/index.js, src/config/ch.sbb.netzkarte/index.js, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/popups/StopPlacePopup/StopPlacePopup.js
=> fix(handicap): translate accessibility note string

src/config/ch.sbb.netzentwicklung/index.js
=> fix(netzentwicklung): remove S&K Planer layer from Netzentwicklung

src/layerInfos/GeltungsbereicheLayerInfo/GeltungsbereicheLayerInfo.js
=> fix(geltungsbereiche): add warranty text to layer infos

src/layerInfos/GeltungsbereicheLayerInfo/GeltungsbereicheLayerInfo.js
=> fix(geltungsbereiche): add text

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/popups/StopPlacePopup/StopPlacePopup.js, src/popups/StopPlacePopup/StopPlacePopup.test.js
=> fix(handicap): prevent popup crash

src/popups/StopPlacePopup/StopPlacePopup.js, src/popups/StopPlacePopup/StopPlacePopup.test.js
=> fix(handicap): update display of alternative transport in handicap overlay

src/config/ch.sbb.netzentwicklung/index.js, src/popups/StopPlacePopup/StopPlacePopup.js, src/popups/StopPlacePopup/StopPlacePopup.test.js
=> fix(netzentwicklung): remove line highlight on layer switch

src/img/railplus_legend_de.url.svg, src/img/railplus_legend_fr.url.svg, src/img/railplus_legend_it.url.svg
=> fix(railplus): update address in railplus PDF legends

src/config/ch.sbb.netzkarte/index.js, src/layers/StationsLayer/StationsLayer.js
=> fix(netzkarte): use metadata tags for station layer source update instead of layer.id/layer.source-layer

src/config/ch.sbb.netzkarte.sandbox/index.js
base_bright_v2_poi (ROKAS POIs) style is deprecated and was replaced by temp_entwicklungsstyle
=> fix(sandbox): use temp_entwicklungsstyle for sandbox topic, rename baselayer to Teststyle

src/config/topics.js
=> fix(railplus): limit maxZoom to 13 in railplus topic

src/layers/MesswagenLayer/MesswagenLayer.js, src/layers/MesswagenLayer/MesswagenLayer.test.js
Open funkmesswagen topic
Set network connection to 3G in dev console
The train should update correctly
=> fix: request new data only when previous request has ended and add a request timeout

src/config/ch.sbb.isb/index.js
=> fix(isb): rename Berner Oberland Bahnen AG to Berner Oberland Bahnen

CHANGELOG.md, package.json, src/config/ch.sbb.isb/index.js, src/layerInfos/EnergiePublicTopicInfo/EnergiePublicTopicInfo.js, src/layerInfos/GeltungsbereicheTopicInfo/GeltungsbereicheTopicInfo.js, src/layerInfos/InfrastrukturTopicInfo/InfrastrukturTopicInfo.js, src/layerInfos/IsbTopicInfo/IsbTopicInfo.js, src/layerInfos/TarifverbundkarteTopicInfo/TarifverbundkarteTopicInfo.js
=> fix(datalinks): add datalink service for ISB, Tarifverbund, Geltungsbereiche, Energie

src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json, src/layerInfos/NetzentwicklungTopicInfo/NetzentwicklungTopicInfo.js
=> fix(netzentwicklung): change info text

src/lang/it.json
=> fix(passagierfrequenzen): correct typo in italian layer name

package.json, src/config/ch.sbb.zweitausbildung/index.js, src/layers/ZweitausbildungPoisLayer/ZweitausbildungPoisLayer.js
=> fix(zweitausbildung): disolve clusters on high zoom levels

cypress/e2e/Search.cy.js, cypress/e2e/ch.sbb.handicap.cy.js, src/components/Share/Share.js, src/components/Share/Share.test.js, src/lang/de.json, src/lang/en.json, src/lang/fr.json, src/lang/it.json
=> fix(Share): replace Twitter icon with X icon, update button titles and translations

package.json, src/menus/TrackerMenu/TrackerMenu.scss, src/popups/PunctualityPopup/PunctualityPopup.js, src/popups/TarifverbundkartePopup/TarifverbundkartePopup.js, yarn.lock
=> fix(TrackerMenu): round delays to minutes, display historic delays

src/utils/trackingUtils.js
=> fix(tracking): update tracking script URLs

src/config/ch.railplus.mitglieder/RailplusExportButton.js
=> chore: update Railplus export quality

src/utils/trackingUtils.js
=> fix(tracking): add missing trafimage-maps.sbb.ch domain to tracking

src/components/Map/Map.js, src/config/ch.sbb.regionenkarte.public/index.js
=> fix(Regionenkarte): prevent line search highlight from disappearing onPointerMove

package.json, src/utils/trackingUtils.js
=> fix(tracking): use window.location.ancestorOrigins to track parent location

cypress/e2e/DataLink.cy.js, package.json, src/config/topics.js, styleguide.config.js
bauprojekte topic will be removed. Until we get further instructions from client we just hide it without removing the code
=> fix(bauprojekte): hide topic

src/layerInfos/GeltungsbereicheTopicInfo/GeltungsbereicheTopicInfo.js
=> fix: update geltungsbereiche datenstand

src/layers/TralisLayer/TralisLayer.js, src/popups/PunctualityPopup/PunctualityPopup.js, src/utils/getDelayString.js, src/utils/getDelayString.test.js
The delay text on the map match th delay text in the RouteSchedule component.
=> fix: round also the delay value on punctuality layers

src/config/ch.sbb.infrastruktur/index.js
=> fix(esenbahninfrastruktur): use layer metadata instead of id for stylelayers filter

src/popups/KilometragePopup/KilometragePopup.js
=> fix: fix safari bug in kilometers popup

.env, src/layers/LevelLayer/LevelLayer.js
OPen sandbox topic and click on levels, the should all use a grey out style except 2D and level 0
=> fix: use level grey out style

public/iframe-download.html, public/iframe-focus.html, public/iframe.html, src/components/MessageListener/MessageListener.js, src/components/Search/SearchInput.js, src/config/ch.railplus.mitglieder/RailplusExportButton.js
=> fix(SearchInput): prevent jumping to iframe by applying autofocus conditionally

.github/workflows/cypress-firefox.yml, cypress/e2e/ch.sbb.tarifverbundkarte.public.cy.js, src/config/ch.sbb.isb/index.js
=> fix(infrastrukturbetreiberinnen): remove STB from standard gauge lines

src/components/FeatureInformation/FeatureInformation.js, src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap, src/popups/StopPlacePopup/StopPlacePopup.js
=> fix(handicap): use aria-live to read handicap popup content

package.json, src/components/Search/SearchService.js, src/searches/Lines/Lines.js, src/searches/Search.js
=> fix(lines search): use generalized geometry for line km search

src/popups/RailplusPopup/RailplusPopup.js
=> fix(railplus): set max-width for logo in popup
