- src/config/appConfig.js
Also remove unused `tileUrl` from config.
> Configure URL for geOps vector tiles for build env

- src/components/FeatureInformation/FeatureInformation.scss
Risky PR ever. Change the padding of the feature-information popup.
This will allow the layer popup element to have an overflow without using a hack.
> FeatureInformation: Don't put the padding on body but on the child

- src/WebComponent.js
- src/components/FeatureInformation/FeatureInformation.js
- src/components/FeatureMenu/FeatureMenu.js
- src/components/LayerInfosDialog/LayerInfosDialog.js
- src/components/MainDialog/MainDialog.js
- src/components/Popup/Popup.js
- src/components/TopicElements/TopicElements.js
- src/components/TopicLoader/TopicLoader.js
- src/components/TrafimageMaps/TrafimageMaps.js
- src/layerInfos/BehigLayerInfo/BehigLayerInfo.js
- src/layerInfos/BehigTopicInfo/BehigTopicInfo.js
- src/layerInfos/ConstructionLayerInfo/ConstructionLayerInfo.js
- src/layerInfos/PunctualityLayerInfo/PunctualityLayerInfo.js
- src/layerInfos/TarifverbundkarteTopicInfo/TarifverbundkarteTopicInfo.js
- src/layerInfos/ZweitausbildungLayerInfo/ZweitausbildungLayerInfo.js
- src/layerInfos/ZweitausbildungRoutesSubLayerInfo/ZweitausbildungRoutesSubLayerInfo.js
- src/layerInfos/ZweitausbildungSubLayerInfo/ZweitausbildungSubLayerInfo.js
- src/layers/BehigLayer/BehigLayer.js
- src/layers/ConstructionLayer/ConstructionLayer.js
- src/layers/ZweitausbildungAbroadLayer/ZweitausbildungAbroadLayer.js
- src/layers/ZweitausbildungPoisLayer/ZweitausbildungPoisLayer.js
- src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js
- src/popups/DeparturePopup/DeparturePopup.js
- src/popups/DeparturePopup/DeparturePopupContent.js
- src/popups/DeparturePopup/DestinationInput.js
- src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.js
- src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.js
Fix for https://github.com/geops/trafimage-maps/pull/453#discussion_r404721037
based on commit https://github.com/geops/trafimage-maps/commit/443540f089d706b2660635673e4a4af413930c6b from handicap
> Gevos/zweitausbildung: use variables from properties instead of env

- src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js
- src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.js
Use the unique label to filter, sort, and compare features.
This fixes the bug where tourist routes with the same bezeichnung were missing in the popup
> Zweitausbildung: Fix listed features in tourist routes popup

- src/config/layers.js
Open the Netzkarte eisenbahninfrastruktur topic, at level 11 the road number should be displayed.
[Style v1](https://maps2.trafimage.ch/ch.sbb.infrastruktur?lang=de&layers=ch.sbb.infrastruktur.gewaesser.group,ch.sbb.infrastruktur.uebrigebahnen.group,ch.sbb.infrastruktur.tochtergesellschaften.group&x=845213.12&y=5955390.34&z=11)
[Style v2](https://deploy-preview-617--dev-trafimage-maps.netlify.com/?lang=de&layers=ch.sbb.infrastruktur.gewaesser.group,ch.sbb.infrastruktur.uebrigebahnen.group,ch.sbb.infrastruktur.tochtergesellschaften.group&x=835677.71&y=5962704.88&z=11)
> Use netzkarte_eisenbahninfrastruktur_v2 style

- src/layers/ZweitausbildungAbroadLayer/FeatureCollection.json
- Switch to topic ch.sbb.zweitausbildung (Development button -> change topic)
- Click on the red feature "Karte D"
- A sharepoint link should open (where we do not have access to)
> Zweitausbildung: Replace link to Karte D

- src/config/topics.js
- Switch to topic ch.sbb.zweitausbildung (Development button -> change topic)
- Zoom in until the zooming stops
- The z value in the permalink should be 13
> Zweitausbildung: Restrict max zoom to 13

- src/config/layers.js
- src/layers/HandicapLayer/HandicapLayer.js
- src/layers/layerHelper.js
Merge changes of https://github.com/geops/trafimage-maps/pull/573 into the relase branch
(resolved merge conflict)
switch to handicap topic and compare if the orange points fit to the basemap
(In zoom 9 and others some stations of the basemap are not displayed)
> Fix handicap overlays (resolved merge conflict for release branch)

- src/layers/ZweitausbildungAbroadLayer/FeatureCollection.json
Forgot to merge into the release branch first
see https://github.com/geops/trafimage-maps/pull/657/
> Zweitausbildung: Replace link to Karte D (merge into release branch)

- src/components/TopicLoader/TopicLoader.js
- src/config/layers.js
Landeskarte & Landeskarte.grau were not visible anymore.
This Pull Request fix it.
> Fix baselayer style filter for netzkarte v3

- src/popups/HandicapPopup/HandicapPopup.scss
1. Open topic handicap
2. Open popup for Bern
3. The long link should overlap the popup border. Instead text-overflow ellipsis is used (...)
4. Other links in this popup should be displayed as before.
> Handicap popup: Restrict links to max width and use text-overflow ellipsis

- package.json
- yarn.lock
When switching from a topic with no base layers (e.g. showcases) to a topic with base layers, the switcher can't set the currentLayer and crashes the app. This has been fixed in react-spatial 0.3.5 by adding currentLayer to the main render condition (renders null if currentLayer is undefined).
> Upgrade react-spatial with Switcher fix 

- src/components/Footer/Footer.js
See TRAFWART-829
The coordinate system name in the footer (MousePosition component) should be CH1903 instead of CH1093
> Fix typo in coordinate system name, rename CH1093 to CH1903 etc.

- src/components/TrafimageMaps/TrafimageMaps.scss
On resolutions between 1200px und 992px (e.g. iPad) the search component container overlaps the menu component when expanded, making it impossible to click the menu. This was caused due to a uniform left: 55px attribute for all mobile devices. The left attribute was adjusted to make it more device responsive.
To test, use the review app and set the resolution to iPad, and other mobile devices and test the menu button while the search bar is expanded
> Search bar overlap fix

- src/components/TrafimageMaps/TrafimageMaps.scss
Fix css to only blink the map, when focusing with tab (and not on pointermove)
> Fix css to only blink the map, when focusing with tab

- src/examples/Casa/README.md
- src/layers/RouteLayer/RouteLayer.js
- src/layers/RouteLayer/RouteLayer.test.js
Previously the route id was added to the selectedRoutIds array for every sequence, causing the routeId to be added multiple times, resulting in having to click multiple times to deselect the feature until it is deselected for the first time (since splice was used on the array, removing only one of the identical indices)
This behaviour was prevented by adding a condition to only add the index on load if it is not already present.
Tests were improved to check whether the flag icon is only set on the last sequence and whether the routeId is removed from the selectedRouteIds array on click
> Fix Route onClick bug + add/improve tests

- src/layers/RouteLayer/RouteLayer.js
- src/layers/RouteLayer/RouteLayer.test.js
The route circle markers are currently displayed at the start and end of each route sequence.
These now render only at the start and end coordinates of each route. Unit tests were adjusted accordingly.
Test: https://deploy-preview-743--trafimage-maps.netlify.app
> Circle markers on start and end of routes only

- src/config/topics.js
- src/examples/Casa/README.md
- src/layers/MapboxStyleLayer/MapboxStyleLayer.test.js
- src/layers/RouteLayer/RouteLayer.js
- src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
Updates: 
* Added a filter option to TrafImageMapboxMap
* loadMbMap() overwritten in TrafimageMapboxMap, added filter handling to remove layers from the style object.
* Updated tests
> Load mbMap with filtered style layers

- src/components/Header/Header.scss
- src/components/Login/Login.js
- src/components/Login/__snapshots__/Login.test.js.snap
To test the length we can simply replace the button text with a long dummy name: test.username_test.de#EXT#
> Fix logged in user name when too long, with ellipsis

- src/layers/RouteLayer/RouteLayer.js
- src/layers/ZoneLayer/ZoneLayer.js
See ROKAS-68
The application should behave the same. The RouteLayer and ZoneLayer should still use the default urls. However, it's possible to change these urls.
> Add configurable url to RouteLayer and ZoneLayer

- src/layers/RouteLayer/RouteLayer.js
Updates: Added the **profile** parameter to CASA routing API requests, fixes erratic routing
Test: 
- Testing can be done in the CASA example of the [style guide review app](https://deploy-preview-801--trafimage-maps.netlify.app/?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.luftbild.group,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.landeskarte.grau&lang=de&layers=&x=925472&y=5920000&z=7#/Examples/Casa%20Map)
- Requests to https://api.geops.io/routing/v1/ should include a profile=sbb parameter
- Routes can be changed by changing route UICs in the CASA example sandbox code (note that the station needs to include the MOT specified in the route)
> Added profile=sbb to CASA routing requests

- src/components/TrafimageMaps/TrafimageMaps.js
- src/components/TrafimageMaps/TrafimageMaps.test.js
This prevents the tracking script from being loaded.
By default no tacking script should be loaded.
> Fix enable tracking

- src/config/layers.js
**Task**: Passenger frequency numbers should be proportional to the circle area instead of the circle radius
**Solution**: Mapbox circle paint properties have no circle-area property, only circle-radius. Hence the square root of the passenger frequency is used to calculate the radius, instead of the absolute values, producing the desired result.
**Test**: Compare passenger frequencies layer in the [review app](url) the prod version and see the difference
> Passenger frequencies - Circle area instead of circle radius

- src/searches/Betriebspunkte/Betriebspunkte.js
- src/searches/HandicapStopFinder/HandicapStopFinder.js
- src/searches/Lines/Lines.js
- src/searches/Locations/Locations.js
- src/searches/Municipalities/Municipalities.js
- src/searches/StopFinder/StopFinder.js
- yarn.lock
...for:
- StopFinder
- Betriebspunkte
- Lines
- Locations
- Municipalities
...which fixes the search in IE with umlauts.
See TRAFMBB-21
Same as https://github.com/geops/react-transit/pull/285 from https://jira.geops.ch/browse/MAPSET-59
- Open review app in IE
- Search for "Zür"
=> The Stationen "Zürich HB" and "Zürich Oerlikon" should appear.
> Encode search queries

- src/components/TrafimageMaps/TrafimageMaps.scss
Bug without ticket
The element .wkp-search must not overlap the menu.
- Open the application at a screen width of .tm-w-l
- Set the cursor into the search field
- Try to click on the arrow of the menu
=> The menu should open
The same should happen for all screen widths.
> Fix menu which was overlapped by the search at large (.tm-w-l) screens

- package.json
- src/popups/HandicapPopup/HandicapPopup.js
- src/searches/HandicapStopFinder/HandicapStopFinder.js
- src/searches/StopFinder/StopFinder.js
In Handicap Topic, when selecting in the search bar station without infos, the popup indicates that there are no infos,
e.g search for 'jungfrauhoch', click on it.
Ticket:TRAFHAND-104
> Infos on empty handicap popup

- package.json
- src/components/FeatureInformation/FeatureInformation.js
- src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap
- src/popups/HandicapPopup/HandicapPopup.js
- src/popups/HandicapPopup/HandicapPopup.scss
- src/popups/HandicapPopup/HandicapPopupElement.js
- src/popups/HandicapPopup/HandicapPopupElement.test.js
- src/popups/HandicapPopup/__snapshots__/HandicapPopupElement.test.js.snap
- yarn.lock
When using a screenreader, the handicap popup content must be read out loud when opened.
Solution inspired from docu:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
Ticket: TRAFWART-910
Tested with ORCA on linux & nvaccess on windows
> Allow handicap popup content to be read by screen reader

- src/examples/Casa/casa.css
Using z-Indices on the zoom-btns (used for recoloring the separating border between zoom in&out on hover) caused them to overlap the SBB-App
Updates: 
- z-Indices were removed
- The border separating the zoom in/out btns is now reset to black on hover
> CASA zoom button fix

- src/layers/RouteLayer/RouteLayer.js
1) Added error message handling when passing non-array data in the popupContent for CASA routes. **DONE**
2) The CASA example also does not reload properly when editing the example (vector layer disappears)
-> resolved here: https://github.com/geops/trafimage-maps/pull/883
> RouteLayer popupContent Error handling

- src/layers/RouteLayer/RouteLayer.js
- src/layers/RouteLayer/RouteLayer.test.js
We want to ignore failed API requests.
> Catch and ignore failed API requests

- src/popups/HandicapPopup/HandicapPopup.js
In Handicap topic station popup, currently the "treppenfrei" equipment string does not include the exceptions in brackets.
**Fix**: The exceptions string was added to the popup.
**Test**: 
- In the [netlify review app](https://deploy-preview-893--dev-trafimage-maps.netlify.app/), switch to Handicap topic and click on Neuchatel station. 
- In the station equipment the "treppenfrei" should be followed by "(ausser Gleis 1)" (in German only) and should be the same as in the "Rampe" equipment. Other stations where this can be tested are e.g. Solothurn, Villeneuve or St-Maurice.
- Most other stations with "treppenfrei" should not render any brackets with exceptions.
> Add "treppenfrei" exceptions in handicap popup

- src/popups/HandicapPopup/HandicapPopup.js
**Issue:** When treppenfrei=true, rampe=true and rampe_ausnahme is defined the ramp exception is shown twice (after "Treppenfrei" string and "Rampe" string)
**Solution:** The ramp exception after "Treppenfrei" is only displayed when ramp=false.
> Handicap popup: Remove ramp exception duplicate

- src/config/layers.js
- Open [?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.dark,ch.sbb.netzkarte.luftbild.group,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.landeskarte.grau&lang=de&layers=ch.sbb.ch_gemeinden&x=798059.4&y=5912573.3&z=12.59](?baselayers=ch.sbb.netzkarte,ch.sbb.netzkarte.dark,ch.sbb.netzkarte.luftbild.group,ch.sbb.netzkarte.landeskarte,ch.sbb.netzkarte.landeskarte.grau&lang=de&layers=ch.sbb.ch_gemeinden&x=798059.4&y=5912573.3&z=12.59)
- Try to hide /show the Municipalities border layer.
---> You should see or not the municipalities border.
> Replace geoserver use by vector tiles

- src/components/Search/SearchService.js
- src/searches/Lines/Lines.js
- src/searches/Lines/Lines.test.js
The Search for line kilometre points is not working and the Search line segments works but doesn't highlight the line on the map.
Fix: 
- Updated the faulty regex for kilometre search (valid searches for line 500 and km 50.1: 500 50.1, 500 +50.1, 500 + 50.1)
- Added Point highlighting when Point is returned (e.g. a kilometer)
- Fixed line highlighting on map by accepting GeometryCollections (as well as MultiLineString)
Test: 
- **500 50.1**, **500 +50.1**, **500 + 50.1** should return a point in lines search results and highlight it on the map on hover
- **500 1-80** should return a line segment in the lines results and highlight the line on hover
> Fix lines Search

- package.json
- src/components/Overlay/Overlay.js
Fix overlay on mobile: Do not block the map when the overlay is open
1. Open the topic Netzentwicklung in the emulator*
2. Click on a colored line 
=> the overlay opens at the bottom
3. Try to interact with the map (pan, zoom, click on features)
=> The Interaction must work.
* Testing on a mobile device did not work for me as the overlay does not open at all for the netlify app, the same for https://github.com/geops/trafimage-maps/pull/928
> Do not block the map when the overlay is open

- src/components/Map/Map.js
- src/components/TopicElements/TopicElements.js
Open an example of the doc and set the topic.elements.popup property to false. There should not be highlight and select effect.
> Deactivate completely pointer events when popup element is disabled

- cypress/integration/Header.spec.js
- src/components/LanguageSelect/LanguageSelect.js
- src/components/ProjectionSelect/ProjectionSelect.js
- src/components/Select/Select.js
- src/components/TopicMenu/TopicMenu.js
- src/components/TopicMenu/TopicMenu.scss
- src/components/TrafimageMaps/TrafimageMaps.scss
- src/config/layers.js
- src/lang/fr.json
Updates:
- Fixed the hideOutline MUI error message by deleting the prop before injecting them
- Using deepMerge to merge the MenuProps. MenuProps injected into the local Select component are deep merged with a default MenuProps object inside the component. This saves us from applying a lot of code when calling the component.
- Using TransintionProps _onEnter_ (as suggested by MUI, since PaperProps _onEnter_ is deprecated). By using this property in the default MenuProps object the dropdown width is now always calculated automatically
> Improve Select

- package.json
- public/index.html
- src/components/FeatureInformation/FeatureInformation.js
- src/components/FeatureInformation/FeatureInformation.test.js
- src/config/layers.js
- src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.scss
- src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.scss
All information displayed on click should be displayed in the right overlay, not the popup(except kilometrage layer)
> Use overlay by default instead of popup

- .env
- package.json
- public/index.html
- src/WebComponent.js
- src/components/TrafimageMaps/TrafimageMaps.js
- src/components/TrafimageMaps/TrafimageMaps.test.js
This PR displays consent banner only when it makes sense and use properly.
It display consent banner:
- if the current domain is the one allowed by OneTrust
- in a same domain iframe, only if the current domain AND the parent domain are the one allowed by OneTrust
- in 3rd party iframe using https, only if the current domain is the one allowed by OneTrust . 
OneTrust Cookies must be defined with SameSite=none and Secure=true
> Add disableCookies and domainConsent properties

- src/searches/StopFinder/StopFinder.js
We always move the first Swiss search result (if there are any) to second position when the search resuslts are collapsed
> fix(station-search): always show first Swiss station in search results when collapsed

- src/layers/PlatformsLayer/PlatformsLayer.js
- src/layers/PlatformsLayer/PlatformsLayer.test.js
When clicking on 2 platforms at a time, some data in the popup were duplicated. So with this PR we only allow one platform to be selected,
> fix: only return one platform at a time

- .github/workflows/cypress-chrome.yml
- src/popups/RegionenkarteSegmentPopup/Av.js
- src/popups/RegionenkarteSegmentPopup/Person.js
Currently changing the AV role in the private _Analgenverantwortliche_ topic causes popup in the public _Koordinatoren Bahnnahes Bauen_ topic to also use that role instead of av_bnb. It is triggered because of the permalink parameter _anlagegattung_.
Fix:
- Ignore permalink parameter when in public topic
> fix(Regionenkarte Public): prevent permalink parameters from using private roles in popup

- package.json
- src/components/LanguageSelect/LanguageSelect.js
- src/components/Select/Select.js
- src/components/TopicLoader/TopicLoader.js
- src/popups/RegionenkarteSegmentPopup/Av.js
Since we update the map on language change the AV popup loses the reference to the AV layer and crashes.
Fix:
- remove the map update on language switch, fixes the popup behaviour
- improve the CSS for the AV dropdown options, prevent it form inflating over the input width 
- add data attributes for cypress tests in gitlab
> fix(Anlagenverantwortliche): remove map update on language switch (fixes the AV popup dropdown)

- src/menus/DirektverbindungenMenu/DvLayerSwitcher.js
open direktverbnindungen iframe topic -> reduce the width of the window to 485
Before:
After:
> fix: add more space when sbb switch are on the same row

- src/components/Overlay/Overlay.js
- src/menus/DirektverbindungenMenu/DvLayerSwitcher.js
Open ch.sbb.direktverbindungen-iframe topic -> reduce the size of the window to mobile -> select a line -> scroll the overlay.
Now the overlay follow the cursor then snap smoothly to the cloest snap breakpoint defined.
> fix: add transition when the overlay snap

- src/config/ch.sbb.netzkarte.sandbox/index.js
When switching to ROKAS-POIs baselayer in the Netzkarte-Sandbox topic, then switching to Netzkarte topic, the POI layer remains visible in mapbox, because both topics use the same layer instances.
Fix: Clone the layers from Netzkarte topic
> fix(Netzkarte Sandbox): clone Netzkarte layers in sandbox topic to prevent residuals on topic switch

- src/config/ch.sbb.netzkarte/index.js
Changed stylelayersFilter in Nahverkehr-Layers in punctuality to be any rail features that are not Fernverkehr.
> fix(punctuality): redefine stylelayersFilter for regional trains in tracker

- src/config/ch.sbb.sts/index.js
- src/menus/StsMenu/StsMenu.js
When switching back to STS validity from STS DV, the hidden layers (e.g. the white line background) layout visibility needs to be reapplied
> fix(STS): ensure hidden layers visibility is applied after switch from STS DV to STS validity

- package.json
- packages/es/.babelrc
- yarn.lock
This PR fixes the tree-shaking of react-icons in project that uses the es folder. So all the react-icons libs is not embedded anymore making the bundle size really big.
> fix: allow proper tree shaking for app using the es folder

- src/layers/PlatformsLayer/PlatformsLayer.js
- src/layers/StationsLayer/StationsLayer.js
Currently the platforms select two features on click, resulting in duplicate popup content in the NetzkartePopup.
Also some polygon nodes are added to the highlighting, which should not be displayed
Both Bugs result from adding the stop_position regex to the StationLayer, so the platforms are selected in StationLayer and in PlatformsLayer
> fix(Haltekanten): remove stop_positions from StationsLayer, use metadata tag in PlatformsLayer

- src/components/FeatureInformation/FeatureInformation.js
- src/utils/useUpdateFeatureInfoOnLayerToggle.js
- src/utils/useUpdateFeatureInfoOnLayerToggle.test.js
When toggling layers the selected features in the overlay and the map should update accordingly. If features are removed from the map they need to be removed from the overlay as well.
> fix(overlay): remove features from overlay when deactivating layers

- package.json
- yarn.lock
Cancelled trains are displayed in gray instead of green on low zoom level (small points)
> fix: use good color for cancelled trains on low zoom level
